name: Shared Release Workflow

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

    
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci || true

      - run: npm publish --access public --provenance
      - run: npm config delete //registry.npmjs.org/:_authToken || true
